module.exports = [
  {
    name: 'August',
    usertag: 'August#2321',
    img: 'August2321.png',
    time: '2019-12-03',
    desc: 'This is the most customisable leveling bot i\'ve used so far. Great work! I love that I\'m able to actually set how often the bot records messages etc.',
  },
  {
    name: 'RapidDarkVenom',
    usertag: 'RapidDarkVenom#9616',
    img: 'RapidDarkVenom9616.png',
    time: '2019-12-08',
    desc: 'Thx for your work. Great Bot. 👍👍',
  },
  {
    name: '}{OЯCRUX ✓',
    usertag: 'Horcrux#6073',
    img: 'Horcrux6073.png',
    time: '2019-12-11',
    desc: 'Outclasses every other bot in terms of features and customisations! 👍',
  },
  {
    name: 'speaker.mp3',
    usertag: 'speaker.mp3#6953',
    img: 'speakermp36953.png',
    time: '2019-12-13',
    desc: 'By far one of the best bots I have ever used 👍👍👍👍👍👍',
  },
  {
    name: 'Mike',
    usertag: 'Mike#4027',
    img: 'Mike4027.png',
    time: '2020-12-13',
    desc: 'Nice bot, love the customizability and the fact that it\'s free 😊 Support\'s very quick too',
  },
  {
    name: 'Kapra',
    usertag: 'kapra#8083',
    img: 'kapra8083.png',
    time: '2019-12-31',
    desc: 'Thank you for listening to the requests. This bot definitely beats any other leveling bot out there',
  },
  {
    name: 'T҉ђ𝔢𝔇𝔞𝔯ƙ₣𝕠𝕩',
    usertag: 'T҉ђ𝔢𝔇𝔞𝔯ƙ₣𝕠𝕩#9393',
    img: 'TheDarkFox9393.png',
    time: '2020-01-08',
    desc: 'This bot offers many features that other bots either do not have or make you pay for. Level roles for example are insanely hard to find in other bots. Mee6, a big competitor to this bot, makes you pay for said feature. This bot also does things better than tatsumaki because you don’t have to worry about some level 255 entering your server and getting free perms. Levels are per server not global. I had a severe issue where I did the “reset server settings” command and the bot stopped functioning, but after @mentioning one of the mods was on my case and resolved it within a day and a half’s time. Safe to say it’s an admirable bot with a semi-decent staff team.',
  },
  {
    name: 'Emi',
    usertag: 'Emi#9805',
    img: 'Emi9805.png',
    time: '2020-01-28',
    desc: 'At the beginning it\'s hard to understand, but you just need to dig into it. I was looking for a bot like this and I spent hours looking for a useful bot and finally found it; free and useful. It offers privileges that MEE6 does not. My server is now going to be a little more fun, and it gives users an incentive to participate in the chat. So far so good, the commands responded quickly and well, I had no problem.',
  },
  {
    name: 'MrDankToasty',
    usertag: 'MrDankToasty#0117',
    img: 'MrDankToasty0117.png',
    time: '2020-01-29',
    desc: 'Amazing bot with the best support I’ve ever received. Can’t say that I would use any other bot. ⭐',
  },
  {
    name: 'Bisti',
    usertag: 'bisti#5913',
    img: 'bisti5913.png',
    time: '2020-01-29',
    desc: 'I love it! FREE 😍',
  },
  {
    name: 'eLFantome',
    usertag: 'eLFantome#3665',
    img: 'eLFantome3665.png',
    time: '2020-01-30',
    desc: 'Was using mee6 but found activityrank and i cant say nothing.. ITS FREE, amazing and they have a great team who give great and fast support for anyone who need help! Keep it up guys',
  },
  {
    name: 'Wise Catto',
    usertag: 'Wise Catto#5544',
    img: 'WiseCatto5544.png',
    time: '2020-02-03',
    desc: 'I absolutely love the bot! So much better than any leveling bot out there this bot needs more love. And on top of that staff here is so much more helpful than most bot servers I use. I can\'t wait to see where this bot goes',
  },
]
