[level]
path = "emoji/level-128.png"

[activityrank]
path = "emoji/logo-128.png"

[deleteduser]
path = "emoji/deleted-user.png"

[message]
path = "emoji/message.png"

[voice]
path = "emoji/voice.png"

[invite]
path = "emoji/invite.png"

[upvote]
path = "emoji/upvote.png"

[bonus]
path = "emoji/bonus.png"
