USE `manager`;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS guildRoute;
DROP TABLE IF EXISTS dbShard;
DROP TABLE IF EXISTS setting;
DROP TABLE IF EXISTS botShardStat;
DROP TABLE IF EXISTS botStat;
DROP TABLE IF EXISTS userRoute;
DROP TABLE IF EXISTS productKey;
