name: Changelog and Bump

on:
  workflow_dispatch:

jobs:
  cog_bump:
    runs-on: ubuntu-latest
    # require main branch to run
    if: github.ref_name == github.event.repository.default_branch
    env:
      GITHUB_USER: piemot
      GITHUB_EMAIL: 84595516+piemot@users.noreply.github.com
      GITHUB_TOKEN: ${{ secrets.PIEMOT_PAT }}
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.PIEMOT_PAT }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Run Cocogitto
        uses: cocogitto/cocogitto-action@v3
        id: release
        with:
          check: false
          release: true
          git-user-email: "${GITHUB_EMAIL}"
          git-user: "${GITHUB_USER}"

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
          token: ${{ secrets.PIEMOT_PAT }}

