name: Changelog and Bump

on:
  workflow_dispatch:

jobs:
  cog_bump:
    runs-on: ubuntu-latest
    # require main branch to run
    if: github.ref_name == github.event.repository.default_branch
    env:
      GITHUB_USER: github-actions[bot]
      GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Bump package versions and produce changelogs
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Run Cocogitto
        uses: cocogitto/cocogitto-action@v3
        with:
          check: false
          release: true
          git-user-email: "${GITHUB_EMAIL}"
          git-user: "${GITHUB_USER}"
